### ISSUE TITLE
Lockscreen Album Art makes systemui unresponsive

### ISSUE THREAD

**Issue by DeadneM** [siavash79/AOSPMods#220]
Hi there, 

I noticed this bug since version 1.1.2 and still present on canary 43.

When playing a music as soon as the music start it will make system UI crash and it will stop the music player.

I tried with other music player and it's the same. The phone gets unresponsive for like 10seconds and go back to lockscreen 

If I disable the lockscreen Album Art. Music player will work as intended and system UI don't crash.

Note that if I play a music and immediately put the screen off the system UI restart but the music player keeps playing then I can listen music but each time the music change the system lags as hell.

**Comment by DeadneM** [comment]
Woops sorry

Device: Pixel 4a
Android version: Android 12
Security patch: May 2022 
Magisk version: 24.3
Lsposed version: 1.8.3

I've tried without other magysk and or lsposed module and it doesn't change.

**Comment by EleoXDA** [comment]
> Woops sorry
> 
> Device: Pixel 4a
> Android version: Android 12
> Security patch: May 2022 
> Magisk version: 24.3
> Lsposed version: 1.8.3
> 
> I've tried without other magysk and or lsposed module and it doesn't change.
> 

Please share a video cast explaining your issue. We can't replicate your issue with our pixel devices and non-pixel devices on AOSP ROMs in our user group.

And also, please share a list of magisk and lsposed modules as well. And also share the lsposed logs from lsposed app.

**Comment by DeadneM** [comment]
https://drive.google.com/file/d/18-97iXB430sNguH6M1xfausqjMOqKFIT/view?usp=drivesdk

Above is the video showing the problem

The first 15sec show which magysk and lsposed module I'm using but again disabling them all appart AOSP mod does the same bug. 

Then I'm showing it's working normally till at 40sec I enable lockscreen Album Art

After that it's inconsistent. It's hard to see but phone freeze and become unresponsive. 
This happen to any music player.
Other player does the same but YouTube music tends to stop playing music 9/10 times.

This bug was introduced after 1.0 stable release lockscreen Album Art worked without issue before.


https://drive.google.com/file/d/18PfwegAGquml95Xy2Abs04qdyncX5PyY/view?usp=drivesdk

Above it's the logs from lsposed

**Comment by EleoXDA** [comment]
This looks very different from what we observe on pixel 3a, 5 and 6 in telegram group.

So far I noticed several interesting parts:

```
	E YT.mlplayer: MedialibPlayer.stopVideo()
	E AudioMediaPlayerWrapper: The callback playback state doesn't match the current state
	E YouTubeMusic: Media progress reported outside media playback: PLAYBACK_PENDING
	E baww    : Phenotype API error. Event # cwpu@861caf41, EventCode: 2 [CONTEXT service_id=51 ]
	E baww    : bavy: 29506: Failed registering with Android package: com.google.android.apps.youtube.music. Config package already registered with a different Android package: com.google.android.youtube
	E baww    : 	at bayh.c(:com.google.android.gms@222055044@22.20.55 (190400-450927560):36)
	E baww    : 	at bayh.a(:com.google.android.gms@222055044@22.20.55 (190400-450927560):3)
	E baww    : 	at bayb.g(:com.google.android.gms@222055044@22.20.55 (190400-450927560):2)
	E baww    : 	at baww.e(:com.google.android.gms@222055044@22.20.55 (190400-450927560):4)
	E baww    : 	at baww.f(:com.google.android.gms@222055044@22.20.55 (190400-450927560):2)
	E baww    : 	at agma.en(:com.google.android.gms@222055044@22.20.55 (190400-450927560):1)
	E baww    : 	at agmg.run(:com.google.android.gms@222055044@22.20.55 (190400-450927560):11)
	E baww    : 	at cdwh.run(:com.google.android.gms@222055044@22.20.55 (190400-450927560):2)
	E baww    : 	at xbe.c(:com.google.android.gms@222055044@22.20.55 (190400-450927560):6)
	E baww    : 	at xbe.run(:com.google.android.gms@222055044@22.20.55 (190400-450927560):7)
	E baww    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	E baww    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	E baww    : 	at xgj.run(:com.google.android.gms@222055044@22.20.55 (190400-450927560):0)
	E baww    : 	at java.lang.Thread.run(Thread.java:920)
```

```
E DatabaseUtils: java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/media/null/albumart
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.getQueryBuilderInternal(MediaProvider.java:5599)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.getQueryBuilder(MediaProvider.java:5041)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.queryInternal(MediaProvider.java:3248)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.query(MediaProvider.java:3176)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.queryForSingleItem(MediaProvider.java:8021)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.openFileAndEnforcePathPermissionsHelper(MediaProvider.java:8143)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.openFileCommon(MediaProvider.java:7780)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.openTypedAssetFileCommon(MediaProvider.java:7840)
E DatabaseUtils: 	at com.android.providers.media.MediaProvider.openTypedAssetFile(MediaProvider.java:7792)
E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:548)
E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1184)
E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
```

```
D ResumeMediaBrowser: No children found for ComponentInfo{com.google.android.apps.youtube.music/com.google.android.apps.youtube.music.mediabrowser.MusicBrowserService}
E MediaResumeListener: Cannot resume with ComponentInfo{com.google.android.apps.youtube.music/com.google.android.apps.youtube.music.mediabrowser.MusicBrowserService}
```

It looks like there is a clash with other magisk/lsposed modules. There are lots and lots of errors in your logs that will definitely slow down your device and worsen your experience. I personally dont advise using multiple mods with clashing options enabled.
I also see that you have several errors in lsposed logs for project themer and aospmods:
```
android.content.res.Resources$NotFoundException: com.android.systemui:layout/quick_qs_status_icons
	at android.content.res.XResources.hookLayout(Unknown Source:41)
	at com.drsants.eggproject.po.Node.handleInitPackageResources(Unknown Source:34)
	at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_InitPackageResources.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at de.robv.android.xposed.XposedInit.cloneToXResources(Unknown Source:2)
	at de.robv.android.xposed.XposedInit.b(Unknown Source:0)
	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(Unknown Source:34)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.createResources(Unknown Source:17)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2415)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1765)
	at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler.<init>(EdgeBackGestureHandler.java:322)
	at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler$Factory.create(EdgeBackGestureHandler.java:988)
	at com.android.systemui.navigationbar.TaskbarDelegate.<init>(TaskbarDelegate.java:149)
	at com.android.systemui.navigationbar.TaskbarDelegate_Factory.newInstance(TaskbarDelegate_Factory.java:33)
	at com.android.systemui.navigationbar.TaskbarDelegate_Factory.get(TaskbarDelegate_Factory.java:25)
	at com.android.systemui.navigationbar.TaskbarDelegate_Factory.get(TaskbarDelegate_Factory.java:8)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.android.systemui.navigationbar.NavigationBarController_Factory.get(NavigationBarController_Factory.java:86)
	at com.android.systemui.navigationbar.NavigationBarController_Factory.get(NavigationBarController_Factory.java:18)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
	at com.google.android.systemui.statusbar.phone.StatusBarGoogle_Factory.get(StatusBarGoogle_Factory.java:562)
	at com.google.android.systemui.statusbar.phone.StatusBarGoogle_Factory.get(StatusBarGoogle_Factory.java:117)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
	at com.android.systemui.dagger.ContextComponentResolver.resolve(ContextComponentResolver.java:99)
	at com.android.systemui.dagger.ContextComponentResolver.resolveSystemUI(ContextComponentResolver.java:92)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:209)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:163)
	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:70)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```
de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.FrameLayout.findViewById(int)' on a null object reference
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at sh.siava.AOSPMods.systemui.NavBarResizer.refreshNavbar(NavBarResizer.java:47)
	at sh.siava.AOSPMods.systemui.NavBarResizer.access$200(NavBarResizer.java:16)
	at sh.siava.AOSPMods.systemui.NavBarResizer$2.afterHookedMethod(NavBarResizer.java:84)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:14)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.systemui.navigationbar.NavigationBar.createView(NavigationBar.java:551)
	at com.android.systemui.navigationbar.NavigationBarController.createNavigationBar(NavigationBarController.java:320)
	at com.android.systemui.navigationbar.NavigationBarController.createNavigationBars(NavigationBarController.java:276)
	at com.android.systemui.statusbar.phone.StatusBar.createNavigationBar(StatusBar.java:1510)
	at com.android.systemui.statusbar.phone.StatusBar.makeStatusBarView(StatusBar.java:1181)
	at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:2419)
	at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:968)
	at com.google.android.systemui.statusbar.phone.StatusBarGoogle.start(StatusBarGoogle.java:389)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:224)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:163)
	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:70)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.FrameLayout.findViewById(int)' on a null object reference
	at com.android.systemui.navigationbar.NavigationBarInflaterView.clearViews(NavigationBarInflaterView.java:463)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 40 more
```
My advice:
A - Disable all other modules in magisk and lsposed and retry logging and videcast.
or
B - Dont use album art blur.

With this setup, I personally advise you to re-check which of the mods are must and which of them can be passed by, as the errors I shared above are only less than 1% of what I observed in your whole logcat

**Comment by DeadneM** [comment]
Here is logs without most mods
 https://drive.google.com/file/d/1931t7z9JgoymtDr4LHWIxIlwFZeiDQDI/view?usp=drivesdk

.Pixel 4a doesn't have blur on stock.
Puting blur to 0% doesn't change anything.
As well as disabling other doesn't change anything 

You see lots of error because it's a verbose logcat. If it was a non detailed log from lsposed you see less.

My phone is laggy just when this bug happens.

I know there's conflict with other module but they're not related to this. For exemple
I use project themer icons pack with AOSP signal icon because I use AOSP mod icon pack it will overlap the chosen signal icon pack when switching Light/Dark theme.

Hope new logs helps

**Comment by siavash79** [comment]
Hi

First of all, I'm happy that system doesn't crash (It only gets super slow). Even blur and grayscale work well

About the reason why it gets slow:

While you play music, system sends a signal of "media metadata has changed" about 3-4 times a second (why that frequently? I've no idea)
Once media metadata change, the mod starts its work and grabs the album art, processes it and puts it on lockscreen. (3-4 times a second!)
upon change of lockscreen picture, the system starts analyzing its colors and refreshing material you colors. (Again!)

That might be a good reason on why your phone gets super slow, and having other theme apps (that contribute in analyzing and updating colors) also increase to the amount of workload your phone gets with lockscreen album art

**Comment by DeadneM** [comment]
I only use project themer with AOSP mod. I have no other themer mod app. The bug is the same when I disable all other magisk lsposed app.

I'm glad system UI doesn't crash too I changed the title of the issue accordingly 

I installed canary v46 I saw a commit related to lockscreen Album Art 

Unfortunately this introduce a new bug where the album art doesn't disappear for the lockscreen wallpaper. The album stay there when there's no notification.

I've tried to play the reduce space keyboard as it also cause problems when both are enabled with hide navbar

I noticed something when the hide navbar option is off it's works without problem 
 
I'm happy to see you're taking this issue into account. I know there's not a lot a pixel 4a owner but it was working well before v1.1.2

**Comment by siavash79** [comment]
Tell me something: did you performance improve after the last canary?

**Comment by siavash79** [comment]
+ try canary 47 and let me know the result

**Comment by DeadneM** [comment]
https://drive.google.com/file/d/1BREfMw5uWHtvc9gtA61C5mLglVzYACSm/view?usp=drivesdk


Nope performance didn't improve on 47 and bug is still there.

Above is the link to a lsposed(non detailed) when I try to play music multiple times with 47 version.


I think something change after V1 on the way AOSP mod handle Monet 

I think the navbar bug (If you have both reduce space keyboard and hide navbar option enabled, hide navbar will stop working when light/dark theme is switched)

The signal icon bug (in AOSP mod when you choose a signal icon pack and a systemui icon pack the signal icon pack stop working when light/dark theme is switched)
 
And Album art lockscreen bug are somehow linked 

After V1 I noticed that when switching Light/Dark there's a lag which seems linked to what you said about the system checking 3/4 times in a second the color of wallpaper

The problem is that it cause lag but the solution isn't in the problem. I mean fixing performance. 

^^ anyway I'll take any solution and I would try any test version to fix the problem. 

I wonder if the problem is also there on a pixel but as pixel 4a hardware is cheaper the lag and CPU stress it cause make system and music app malfunction when other pixel pass that problem without really noticing it

**Comment by EleoXDA** [comment]
I can replicate the reduce keyboard + hide navbar issue you mentioned. But the lag as you mentioned should not come from pixel 4a cheap hardware, as I am also using pixel 3aXL which has even slower hardware. It also doesn't have blur on stock and it is even older than pixel 4. And I cannot replicate your unresponsive UI event there as well. I cannot see it both in pixel 6 and 3aXL. So it is not related to the performance of your device.

**Comment by EleoXDA** [comment]
Is there any update with the latest canary?

**Comment by DeadneM** [comment]
No it's still the same. Version after release V1.0 have the same weird behavior where the system UI is refreshing when playing music, switching Light dark theme. Also hide nav bar is still inconsistent

**Comment by EleoXDA** [comment]
Weird. On my pixel 3aXL (which is slower than yours) I got 0 slowness. I guess that is it

**Comment by DeadneM** [comment]
Does 3xl have monet ?

**Comment by EleoXDA** [comment]
All in all, if you get unresponsive UI, turn off album art lockscreen
