### ISSUE TITLE
SystemUI crashes and random restarts on Pixel Experience Plus

### ISSUE THREAD

**Issue by osamasaleem94** [siavash79/AOSPMods#345]
*Please note: At the time being, only bug reports from Pixel Stock firmware, or Pixel Experience will be considered. Bug reports from other firmwares will only be taken into account if also reported from one of the supported roms.*

**Describe the bug**
Repeated and random crashing of SystemUI with occasional restarts, sometimes while not in use.

**To Reproduce**
1. Flash Pixel Experience Plus or LineageOS
2. Use the phone phone without any other Magisk or Lsposed Mods
3. Wait for the phone to crash

**Expected behavior**
No SystemUI crashes

**Screenshots**
Not applicable

 - Device: Samsung Galaxy A52 4G
 - OS: Pixel Experience 12.1, August Patch

**LSPosed Log**
Unable to get the LSposed logs because I had already uninstalled the module but here's the System UI crash log via Scoop:

FATAL EXCEPTION: Thread-243
Process: com.android.systemui, PID: 2934
de.robv.android.xposed.XposedHelpers$InvocationTargetError: com.android.internal.widget.LockPatternUtils$RequestThrottledException
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at sh.siava.AOSPMods.systemui.EasyUnlock$1.lambda$afterHookedMethod$1(EasyUnlock.java:64)
	at sh.siava.AOSPMods.systemui.EasyUnlock$1$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.android.internal.widget.LockPatternUtils$RequestThrottledException
	at com.android.internal.widget.LockPatternUtils.checkCredential(LockPatternUtils.java:472)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)

**Comment by siavash79** [comment]
Can you please attach lsposed log file

**Comment by osamasaleem94** [comment]
#> Can you please attach lsposed log file

[Uploading LSPosed_2022-09-09T22_02_44.085.zip…]()

[Uploading LSPosed_2022-09-09T22_02_59.821.zip…]()

**Comment by siavash79** [comment]
Apparently the log file isn't uploaded correctly

**Comment by siavash79** [comment]
Anyway: disabling easyunlock will solve your problem
