### ISSUE TITLE
Brightness slider auto-slides back

### ISSUE THREAD

**Issue by xxz3** [siavash79/AOSPMods#469]
### Describe the issue

When adjusting brightness slider, almost every time it slides back where it was previously

### Steps to reproduce

As seen in video: 

https://imgur.com/a/EAxaxAE

### Expected bahavior

Slider stops where finger is

### Your device setup (Please take some time to give correct information here)

- Google pixel 7
- Android 13 (TD1A.221105.001)
- AOSPMods canary-173
- Magisk 25.2
- lsposed 1.8.5

### Logs

```
[ 2022-11-29T19:32:57.557    10216:  2000:  2000 E/LSPosed-Bridge  ] java.lang.NoSuchFieldError: com.android.keyguard.KeyguardUpdateMonitor#mBouncer
	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.j(Unknown Source:0)
	at de.robv.android.xposed.c.get(Unknown Source:28)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.getBooleanField(Unknown Source:4)
	at sh.siava.AOSPMods.systemui.FingerprintWhileDozing$1.afterHookedMethod(FingerprintWhileDozing.java:54)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.shouldListenForFingerprint(Unknown Source:15)
	at com.android.keyguard.KeyguardUpdateMonitor.updateFingerprintListeningState(KeyguardUpdateMonitor.java:22)
	at com.android.keyguard.KeyguardUpdateMonitor$14.handleMessage(KeyguardUpdateMonitor.java:446)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2022-11-29T19:36:05.241    10216:  2000:  2000 E/LSPosed-Bridge  ] java.lang.NoSuchFieldError: com.android.keyguard.KeyguardUpdateMonitor#mBouncer
	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.j(Unknown Source:0)
	at de.robv.android.xposed.c.get(Unknown Source:28)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.getBooleanField(Unknown Source:4)
	at sh.siava.AOSPMods.systemui.FingerprintWhileDozing$1.afterHookedMethod(FingerprintWhileDozing.java:54)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.shouldListenForFingerprint(Unknown Source:15)
	at com.android.keyguard.KeyguardUpdateMonitor.updateFingerprintListeningState(KeyguardUpdateMonitor.java:22)
	at com.android.keyguard.KeyguardUpdateMonitor.updateBiometricListeningState(KeyguardUpdateMonitor.java:0)
	at com.android.keyguard.KeyguardUpdateMonitor$14.handleMessage(KeyguardUpdateMonitor.java:160)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2022-11-29T19:37:28.711    10216:  2000:  2000 E/LSPosed-Bridge  ] java.lang.NoSuchFieldError: com.android.keyguard.KeyguardUpdateMonitor#mBouncer
	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.j(Unknown Source:0)
	at de.robv.android.xposed.c.get(Unknown Source:28)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.getBooleanField(Unknown Source:4)
	at sh.siava.AOSPMods.systemui.FingerprintWhileDozing$1.afterHookedMethod(FingerprintWhileDozing.java:54)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.shouldListenForFingerprint(Unknown Source:15)
	at com.android.keyguard.KeyguardUpdateMonitor.updateFingerprintListeningState(KeyguardUpdateMonitor.java:22)
	at com.android.keyguard.KeyguardUpdateMonitor.updateBiometricListeningState(KeyguardUpdateMonitor.java:0)
	at com.android.keyguard.KeyguardUpdateMonitor$14.handleMessage(KeyguardUpdateMonitor.java:160)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2022-11-29T19:48:34.719    10419: 18796: 18796 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-29T19:48:34.784    10419: 18796: 18796 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-29T19:48:34.788    10419: 18796: 18796 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-29T19:48:34.790    10419: 18796: 18796 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-29T19:48:34.869    10419: 18796: 18796 I/LSPosed-Bridge  ] AOSPMods Version: canary-173
[ 2022-11-29T19:48:34.886    10419: 18796: 18796 I/LSPosed-Bridge  ] AOSPMods Records: 161

```

Here i can only see something related to fingerprint reader while screen off, but this feature is off in my settings.

**Comment by EleoXDA** [comment]
Please answer all questions in bugreport and also share lsposed.zip file

**Comment by EleoXDA** [comment]
This does not happen on any of the tester's google pixel 7 device and thus we need to see all the information from you

**Comment by xxz3** [comment]
[LSPosed_2022-11-29T19_53_47.745577.zip](https://github.com/siavash79/AOSPMods/files/10117466/LSPosed_2022-11-29T19_53_47.745577.zip)

Here is export

**Comment by EleoXDA** [comment]
Unfortunately none of our pixel 7 users can reproduce your issue. And they also cannot reproduce the logs that you get about com.android.keyguard.KeyguardUpdateMonitor#mBouncer

Could you please reupload a new untouched LSposed zip?

**Comment by other909** [comment]
I have this bug too. It is happening together with white clock in notification panel at the same time. I have Pixel 7 Pro, Android 13 last ofucial build.
When i turn off and than turn on white notification panel option, both of the options is getting normal, but after 12-24 hours clock turns white and brightness slider comes back from bottom to top.

**Comment by EleoXDA** [comment]
> I have this bug too. It is happening together with white clock in notification panel at the same time. I have Pixel 7 Pro, Android 13 last ofucial build.
> When i turn off and than turn on white notification panel option, both of the options is getting normal, but after 12-24 hours clock turns white and brightness slider comes back from bottom to top.

That is not even what this bugreport is about. And again, if you have a bug to report (which you seem to have) please open a new bugreport and fill in all the information. 

As about this bugrepory, as several pixel 7 testeds have said they don't get it, and the user who reported hasn't replied yet, it is on hold

**Comment by EleoXDA** [comment]
No answer and no extend on the bugreport. Closed until new valuable response or data
