### ISSUE TITLE
Hide navigation bar is not working 

### ISSUE THREAD

**Issue by hcosserat** [siavash79/AOSPMods#557]
### Describe the issue

Toggling the Hide navigation bar on and off won't change anything. The screen will freeze for half a second but that bar won't disappear.

### Steps to reproduce

1. Go to Navigation bar
2. Click Hide navigation bar
3. Observe
![Screenshot_20230326-201002](https://user-images.githubusercontent.com/86538172/227795505-afdf1ca9-5e96-4c40-919b-3313ca9c9fa9.png)

### Expected bahavior

The navigation bar should go away when turning the switch on.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6a, stock firmware, February 2023 security update
- Android 13.0
- 5 February 2023
- Magisk 25.2
- AFWall+, AirMusic, AOSPMods, Audio Headquarters, [SharedUID] Automate, Button Mapper, Custom Quick Settings, Logcat Reader, Material Files, Migrate GPE, Pixel Launcher, Revanced Manager, SAI, SDMaid, Swift Backup, [SharedUID] System UI
- AOSPMods (Canary 232), AudioHQ (rev 0.91),  BCR (1.37), HiddenSettings (0.0.4), James DSP Manager (4.6), Shamiko (0.6), Universal SafetyNet Fix (2.3.1), Zygisk - LSPosed (1.8.6)
- LSPosed : API version
100

Xposed API call protection
Enabled

Dex Optimizer Wrapper
Unsupported (SELinux is permissive)

Framework version
1.8.6 (6865)

Manager version
1.8.6 (6865)

System version
13 (API 33)

Device
Google Google Pixel 6a 

System ABI
arm64-v8a
- AOSP Mods (canaray-232), Core Patch (4.2)

### Logs

----part 2 start----
[ 2023-03-26T19:53:19.225    10494: 24701: 24701 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2023-03-26T19:53:19.287    10494: 24701: 24701 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2023-03-26T19:53:19.289    10494: 24701: 24701 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2023-03-26T19:53:19.289    10494: 24701: 24701 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2023-03-26T19:53:19.378    10494: 24701: 24701 I/LSPosed-Bridge  ] AOSPMods Version: canary-232
[ 2023-03-26T19:53:19.383    10494: 24701: 24701 I/LSPosed-Bridge  ] AOSPMods Records: 129
[ 2023-03-26T19:53:27.747    10213:  1985:  1985 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: Resource ID #0x7f080093
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:235)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:991)
	at android.content.res.Resources.getDrawable(Resources.java:931)
	at androidx.core.content.res.ResourcesCompat$Api21Impl.getDrawable(ResourcesCompat.java:705)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:137)
	at sh.siava.AOSPMods.systemui.NotificationExpander.updateFooterBtn(NotificationExpander.java:144)
	at sh.siava.AOSPMods.systemui.NotificationExpander.access$800(NotificationExpander.java:30)
	at sh.siava.AOSPMods.systemui.NotificationExpander$2.afterHookedMethod(NotificationExpander.java:109)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.updateColors(Unknown Source:8)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateDecorViews(NotificationStackScrollLayout.java:82)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController$3.onThemeChanged(NotificationStackScrollLayoutController.java:35)
	at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:358)
	at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at dlg.xSlGQm.zFy.IgzM.SnCZLEszp.HookBridge.invokeOriginalMethod(Native Method)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.onConfigurationChanged(Unknown Source:11)
	at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:242)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:216)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:128)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5970)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-03-26T19:53:27.748    10213:  1985:  1985 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: Resource ID #0x7f080093
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:235)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:991)
	at android.content.res.Resources.getDrawable(Resources.java:931)
	at androidx.core.content.res.ResourcesCompat$Api21Impl.getDrawable(ResourcesCompat.java:705)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:137)
	at sh.siava.AOSPMods.systemui.NotificationExpander.updateFooterBtn(NotificationExpander.java:144)
	at sh.siava.AOSPMods.systemui.NotificationExpander.access$800(NotificationExpander.java:30)
	at sh.siava.AOSPMods.systemui.NotificationExpander$1.afterHookedMethod(NotificationExpander.java:100)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.onFinishInflate(Unknown Source:8)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at java.lang.reflect.Method.invoke(Native Method)
	at dlg.xSlGQm.zFy.IgzM.SnCZLEszp.HookBridge.invokeOriginalMethod(Native Method)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.inflateFooterView(NotificationStackScrollLayout.java:10)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController$3.onThemeChanged(NotificationStackScrollLayoutController.java:42)
	at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:358)
	at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at dlg.xSlGQm.zFy.IgzM.SnCZLEszp.HookBridge.invokeOriginalMethod(Native Method)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.onConfigurationChanged(Unknown Source:11)
	at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:242)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:216)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:128)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5970)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-03-26T19:53:30.740    10213:  1985:  1985 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: Resource ID #0x7f080093
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:235)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:991)
	at android.content.res.Resources.getDrawable(Resources.java:931)
	at androidx.core.content.res.ResourcesCompat$Api21Impl.getDrawable(ResourcesCompat.java:705)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:137)
	at sh.siava.AOSPMods.systemui.NotificationExpander.updateFooterBtn(NotificationExpander.java:144)
	at sh.siava.AOSPMods.systemui.NotificationExpander.access$800(NotificationExpander.java:30)
	at sh.siava.AOSPMods.systemui.NotificationExpander$2.afterHookedMethod(NotificationExpander.java:109)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.updateColors(Unknown Source:8)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateDecorViews(NotificationStackScrollLayout.java:82)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController$3.onThemeChanged(NotificationStackScrollLayoutController.java:35)
	at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:358)
	at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at dlg.xSlGQm.zFy.IgzM.SnCZLEszp.HookBridge.invokeOriginalMethod(Native Method)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.onConfigurationChanged(Unknown Source:11)
	at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:242)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:216)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:128)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5970)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-03-26T19:53:30.741    10213:  1985:  1985 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: Resource ID #0x7f080093
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:235)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:991)
	at android.content.res.Resources.getDrawable(Resources.java:931)
	at androidx.core.content.res.ResourcesCompat$Api21Impl.getDrawable(ResourcesCompat.java:705)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:137)
	at sh.siava.AOSPMods.systemui.NotificationExpander.updateFooterBtn(NotificationExpander.java:144)
	at sh.siava.AOSPMods.systemui.NotificationExpander.access$800(NotificationExpander.java:30)
	at sh.siava.AOSPMods.systemui.NotificationExpander$1.afterHookedMethod(NotificationExpander.java:100)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.onFinishInflate(Unknown Source:8)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at java.lang.reflect.Method.invoke(Native Method)
	at dlg.xSlGQm.zFy.IgzM.SnCZLEszp.HookBridge.invokeOriginalMethod(Native Method)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.inflateFooterView(NotificationStackScrollLayout.java:10)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController$3.onThemeChanged(NotificationStackScrollLayoutController.java:42)
	at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:358)
	at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at dlg.xSlGQm.zFy.IgzM.SnCZLEszp.HookBridge.invokeOriginalMethod(Native Method)
	at FBX.P.tX.S.nVY.LhAVeSw.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.onConfigurationChanged(Unknown Source:11)
	at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:242)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:216)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:128)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5970)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by EleoXDA** [comment]
Please re-read the #bugreport note in telegram group. It explicitly asks for LSPosed.zip file that is created by going to LSPosed app's logs panel and clicking "save" button at top of app screen.

Please generate such a zip file and share it here
