### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by woshigenm** [siavash79/AOSPMods#592]
### Describe the issue

 java.lang.NullPointerException

### Steps to reproduce

1.Install in magisk
2.reboot

### Expected bahavior

work well

### Your device setup (Please take some time to give correct information here)

Device Brand]: Redmi
[Os]:crDroid
[Device Model]: 22041211AC
[Display]: TQ2A.230405.003.E1
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN_#Hans
[Process ID]: 6515
[CPU ABI]: none
[Lsposed]:1.8.6
[Package Name]: sh.siava.AOSPMods
[Version Name]: 2.7.2
[Version Code]: 233
[Error Type]: JVM
[Crash Time]: 2023-05-02T17:39:03.913
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:270)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6675)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

### Logs

`
[sh.siava.AOSPMods_2023-05-02T17_39_03.913.log](https://github.com/siavash79/AOSPMods/files/11371808/sh.siava.AOSPMods_2023-05-02T17_39_03.913.log)
`

**Comment by EleoXDA** [comment]
Crdroid was never supported. Read readme file
