### ISSUE TITLE
[Bug] Spamming java.lang.ClassCastException when notification shade brought down

### ISSUE THREAD

**Issue by TheSunCat** [siavash79/AOSPMods#661]
### Describe the issue

When dragging notification shade down, this message is spammed in logcat

### Steps to reproduce

1. Install AOSP mods
2. Run `adb logcat` or other way to view logcat
3. Drag down the notification shade
4. Observe

### Expected bahavior

Logs should not be spammed

### Your device setup (Please take some time to give correct information here)

- Google Pixel 3a
- Android 13
- LineageOS 20-20230622-UNOFFICIAL-sargo 
- Magisk v26.1
- AOSPMods 2.4.1, Amaze, App Manager, Aurora Store, Fox's Magisk Module Manager, InviZible Pro, Logcat Reader, Neo Store, [SharedUID] System UI, [SharedUID] Termux
- AOSP Mods (Full version) 2.4.1, Systemless Hosts 1.0, Universal SafetyNet Fix 2.4.0-MOD_1.2, Zygisk - LSPosed 1.8.6 (6712)
- LSposed 1.8.6 (6712)
- AOSP Mods 2.4.1, Force Dark 2, Location Indicator Whitelist 1.1, VendettaXposed 1.1.4, XPrivacyLua 1.35

### Logs

```
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: java.lang.ClassCastException: com.android.systemui.statusbar.phone.NotificationIconContainer cannot be cast to android.widget.FrameLayout
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at sh.siava.AOSPMods.utils.NotificationIconContainerOverride.calculateIconXTranslations(NotificationIconContainerOverride.java:129)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at sh.siava.AOSPMods.systemui.StatusbarMods$5.beforeHookedMethod(StatusbarMods.java:501)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at LSPHooker_.calculateIconXTranslations(Unknown Source:8)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at com.android.systemui.statusbar.NotificationShelf.updateAppearance(NotificationShelf.java:772)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at com.android.systemui.statusbar.NotificationShelf$ShelfState.applyToView(NotificationShelf.java:26)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.applyCurrentState(NotificationStackScrollLayout.java:18)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout$1.onPreDraw(NotificationStackScrollLayout.java:2671)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1182)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3654)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:942)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:201)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:288)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-14 16:25:13.639  2388  2388 E LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by EleoXDA** [comment]
LOS not supported

**Comment by EleoXDA** [comment]
Already mentioned in the bugreport template that you filled:

![Screenshot_20230714-164225.png](https://github.com/siavash79/AOSPMods/assets/27622683/c091390a-b66a-4cbf-b7df-78ce2943a221)

**Comment by TheSunCat** [comment]
Somehow missed that, sorry!

**Comment by EleoXDA** [comment]
No problem

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
