### ISSUE TITLE
beyond frequent issue

### ISSUE THREAD

**Issue by Itsfitts** [siavash79/AOSPMods#664]
randomly began, maybe after an OTA. Tried uninstall/reinstall, etc. next step is factory restore.

java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.Clock#updateClock()
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.f(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:30)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:4)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:4)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods.lambda$updateClock$0$sh-siava-AOSPMods-modpacks-systemui-StatusbarMods(StatusbarMods.java:434)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods$$ExternalSyntheticLambda4.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by EleoXDA** [comment]
Please open new issue and follow the instructions of the bugreport template

**Comment by EleoXDA** [comment]
![image](https://github.com/siavash79/AOSPMods/assets/27622683/8ebc8f69-4fd1-4d20-ac9e-f57479e3757d)
