### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by anuraag488** [siavash79/AOSPMods#697]
### Describe the issue

AOSPMods app crashes when doing some changes

### Steps to reproduce

Open Aospmods
Change any settings
App will crash

### Your device setup (Please take some time to give correct information here)

Redmi Note 9 Pro Max

Android 13 LineageOS 20.0 Official with August security
AOSPMods 3.0.0
Lsposed 1.9.1

### Logs

```
Crash unexpectedly: java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.Clock#updateClock()
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.f(Unknown Source:0)
	at GEq.tasILc.KM.A.g.ENjk.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.callMethod(SourceFile:2)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods.lambda$updateClock$0$sh-siava-AOSPMods-modpacks-systemui-StatusbarMods(StatusbarMods.java:475)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods$$ExternalSyntheticLambda4.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

```
java.lang.NoSuchMethodError: com.android.settingslib.fuelgauge.BatteryStatus#getChargingSpeed(android.app.ContextImpl)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.f(Unknown Source:0)
	at GEq.tasILc.KM.A.g.ENjk.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at GEq.tasILc.KM.A.g.ENjk.XposedHelpers.callMethod(SourceFile:2)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods$9$1.afterHookedMethod(StatusbarMods.java:638)
	at GEq.tasILc.KM.A.g.ENjk.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.handleMessage(Unknown Source:11)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by EleoXDA** [comment]
LineageOS was never supported. Please at least read ReadMe file

**Comment by EleoXDA** [comment]
> I know it's not compatible but atleast you should check why those hooks are called while relevant preferences are turned off. I think hooks should be only applied when relevant preferences are enabled.

they are relevant but not in LineageOS. Since it is not compatible it throws an error.

**Comment by devnoname120** [comment]
Interestingly there is the same exception on PixelOS 14.0-20240128-1649 on the Xiaomi Mi Note 10 Lite phone. I wonder why it happens even though PixelOS is supposed to be a Google Pixel port that is as close as possible from the real thing.

**Comment by EleoXDA** [comment]
> Interestingly there is the same exception on PixelOS 14.0-20240128-1649 on the Xiaomi Mi Note 10 Lite phone. I wonder why it happens even though PixelOS is supposed to be a Google Pixel port that is as close as possible from the real thing.
> 
> ```
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: java.lang.NoSuchMethodError: com.android.settingslib.fuelgauge.BatteryStatus#getChargingSpeed(android.app.ContextImpl)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.XposedHelpers.f(Unknown Source:0)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.c.get(Unknown Source:12)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at java.util.Optional.orElseThrow(Optional.java:404)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.XposedHelpers.findMethodBestMatch(SourceFile:4)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.XposedHelpers.findMethodBestMatch(SourceFile:5)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.XposedHelpers.callMethod(SourceFile:1)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at sh.siava.pixelxpert.modpacks.systemui.BatteryDataProvider$2.afterHookedMethod(BatteryDataProvider.java:78)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at DQEXP.zTKDOR.II.Q.vwJG.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at J.callback(Unknown Source:294)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at LSPHooker_.constructor(Unknown Source:18)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at com.android.keyguard.KeyguardUpdateMonitor$10.onReceive(go/retraceme 46cd2b3ddec0d6dc52bf72e0576b6a6d75e37cd0a408dcb37a358b17b4d40b02:95)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at com.android.systemui.broadcast.ActionReceiver$onReceive$1$1$1.run(go/retraceme 46cd2b3ddec0d6dc52bf72e0576b6a6d75e37cd0a408dcb37a358b17b4d40b02:22)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:294)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:205)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> 1708104015.624 10174  2749  2749 E LSPosed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:958)
> ```

No idea until you start a new bugreport with requested info

**Comment by devnoname120** [comment]
@EleoXDA PixelOS isn't supported, is it? I'm happy to create a new big report if needed.

**Comment by EleoXDA** [comment]
> @EleoXDA PixelOS isn't supported, is it? I'm happy to create a new bug report if needed.

Obviously not. And one more note:
No matter what developers say, neither PixelOS, nor Pixel Experience, or any other custom ROM where developers say "it is "Google Pixel port" or "copy of Google Pixel software", or "basically Google Pixel Firmware", neither of them are true.

So, yes. PixelOS is not supported.

**Comment by devnoname120** [comment]
Makes sense. I wish AOSP was ported to my phone model, but unfortunately it isn't and I don't think it will ever be... I will try to open a bug report on their side to see if they can fix it.

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
