### ISSUE TITLE
Null object reference on sh.siava.AOSPMods.Utils.batteryStyles.BatteryDrawable.setFastCharging(boolean)

### ISSUE THREAD

**Issue by old4error** [siavash79/AOSPMods#88]
Just checked lsposed logs and saw this error

![Screenshot_20220424-191629_LSPosed](https://user-images.githubusercontent.com/58698398/164985874-dcadf938-10ab-41d7-955d-3f9e4aa4c778.png)
[LSPosed_2022-04-24T19_10_14.959.zip](https://github.com/siavash79/AOSPMods/files/8550063/LSPosed_2022-04-24T19_10_14.959.zip)

**Comment by old4error** [comment]
btw rom:arrow os 12.1 device: poco x3 pro (vayu)

**Comment by siavash79** [comment]
Can you please share some data with me:

Which battery style did you select?

Did the style work correctly or did you experience any visible problems?

Had you changed your battery style during the last systemUI restart and finding this error message?

**Comment by old4error** [comment]
This error appears while booting and when i try to change battery style icon. And after that systemui crashes (i don't think that this is systemui reboot, because if i enable percentage, it doesn't reboot) and gives another error:
[ 2022-04-25T06:43:00.385    10102: 14582: 14582 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Attempt to invoke virtual method 'void sh.siava.AOSPMods.Utils.batteryStyles.BatteryDrawable.setShowPercent(boolean)' on a null object reference
	at sh.siava.AOSPMods.systemui.BatteryStyleManager.refreshBatteryIcons(BatteryStyleManager.java:127)
	at sh.siava.AOSPMods.systemui.BatteryStyleManager.updatePrefs(BatteryStyleManager.java:119)
	at sh.siava.AOSPMods.XPrefs.loadEverything(XPrefs.java:43)
	at sh.siava.AOSPMods.XPrefs.lambda$static$0(XPrefs.java:21)
	at sh.siava.AOSPMods.XPrefs$$ExternalSyntheticLambda0.onSharedPreferenceChanged(Unknown Source:0)
	at com.crossbowffs.remotepreferences.RemotePreferences$PreferenceContentObserver.onChange(RemotePreferences.java:522)
	at android.database.ContentObserver.onChange(ContentObserver.java:169)
	at android.database.ContentObserver.onChange(ContentObserver.java:187)
	at android.database.ContentObserver.onChange(ContentObserver.java:202)
	at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
	at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by old4error** [comment]
> Just checked lsposed logs and saw this error
> 
> ![Screenshot_20220424-191629_LSPosed](https://user-images.githubusercontent.com/58698398/164985874-dcadf938-10ab-41d7-955d-3f9e4aa4c778.png) [LSPosed_2022-04-24T19_10_14.959.zip](https://github.com/siavash79/AOSPMods/files/8550063/LSPosed_2022-04-24T19_10_14.959.zip)

And this error comes after rebooting with default icon

**Comment by siavash79** [comment]
Fixed in 66af4613a1e49330455ae1e084288241a6a7e8de
